name: build-and-publish

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Restore Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Set Version Number
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '0.0.0-PLACEHOLDER'
          replace: '1.0.${{ github.run_id }}'
          include: '.*/package.json'
      - name: Build Package
        run: yarn build
      - name: Prepare Publish
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish Package
        run: yarn publish dist/package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
